serviceAccount:
  create: true

deps:
  cassandra: true
  cdb: true
  kafka-v5: true

kafka-v5:
  fullnameOverride: kafka-v5
  zookeeper:
    fullnameOverride: zookeeper-v3

  
############################
### required from pix-imgapi
cassandra:
  fullnameOverride: cassandra-pix-imgapi
  image:
    repository: reg-hk.agodadev.io/pix/cassandra
    tag: "3.11"
  resources:
    limits:
      cpu: 4
      memory: 20Gi
    requests:
      cpu: 4
      memory: 20Gi
  
############################
### required from npcindexer
cdb:
  fullnameOverride: cdb-npc
  image:
    repository: reg-hk.agodadev.io/dbdev/prod_sql_cdb_data_hotel-list-npc
    tag: latest
  resources:
    limits:
      cpu: 5
      memory: 30Gi
    requests:
      cpu: 5
      memory: 30Gi
  logForwarderJob:
    enabled: false
