# rabbitmq-ha:
#   clusterDomain: hkci-k8s-a.local

rabbitmq-ha:
  clusterDomain: hk-aiab-2b.local
  rbac:
    create: true
    pspEnabled: true

global:
  ingress:
    class: istio
    cluster: hk-aiab-2b.agoda.local
    pathType: Prefix

# rbac:
#   create: true
#   pspEnabled: false
#   pspUseAppArmor: false    
##################

propertyapi:
  npc:
    host: npcapiv2
  rbac:
    create: true
    pspEnabled: true

propertysearch:
  npc:
    host: npcapiv2
  rbac:
    create: true
    pspEnabled: true

propertyapi-stream:
  npc:
    host: npcapiv2
  rbac:
    create: true
    pspEnabled: true

dfapi-stream:
  alternateStartMode: stream
  clustermode: false
  rbac:
    create: true
    pspEnabled: true

landing-clay:
  extraEnvs:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: ASPNETCORE_URLS
    value: http://+:5000
  rbac:
    create: true
    pspEnabled: true

# prevent OOMKilled
cassandra:
  resources:
    limits:
      cpu: 1
      memory: 20Gi
    requests:
      cpu: 1
      memory: 20Gi
    rbac:
      create: true
      pspEnabled: true

cdb:
  fullnameOverride: cdb-pinto
  rbac:
    create: true
    pspEnabled: true

cdb-ceph:
  fullnameOverride: cdb
  resources:
    limits:
      cpu: 4
      memory: 20Gi
    requests:
      cpu: 4
      memory: 20Gi
  rbac:
    create: true
    pspEnabled: true

############################
### required from supply-ota
connectivity-init-mssql-data:
  cdb:
    host: cdb-pinto
  rbac:
    create: true
    pspEnabled: true

supply-ota:
  cdb:
    host: cdb-pinto
  rbac:
    create: true
    pspEnabled: true

############################
### required from pix-imgapi
pix-imgapi:
  cassandra:
    host: cassandra-pix-imgapi
  rbac:
    create: true
    pspEnabled: true

############################
### required from flapi
flapi:
  # cassandra:
  #   host: cassandra-flapi
  parent:
    configs:
      - ../infrastructure/src/main/resources/application.conf
      - ../infrastructure/src/main/resources/dev-qa.conf
  rbac:
    create: true
    pspEnabled: true

############################
### required from npcindexer
npcindexer:
  cdb:
    host: cdb-npc 
  rbac:
    create: true
    pspEnabled: true

npces: 
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 4
      memory: 4Gi
  rbac:
    create: true
    pspEnabled: true
